version: '3.1'

services:

  postgres:
    image: postgres
    restart: unless-stopped
    tty: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./postgres-initdb:/docker-entrypoint-initdb.d